CC     = gcc
CFLAGS = -O3 -Wall -Werror -pedantic-errors
all:
	$(CC) $(CFLAGS) -o chatclient chatclient.c
	$(CC) $(CFLAGS) -o chatserver chatserver.c
clean:
	rm -f chatclient chatclient.exe chatserver chatserver.exe

